export const CATALOGUE = [
  {
    code: "ИСЖ 1",
    name: 'ИСЖ ""Драйвер гарантия"" в рублях на 5 лет',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n4,7%\n5,2%",
    return: "5.20%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,000,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 2",
    name: 'ИСЖ ""Драйвер гарантия"" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,93%\n1,23%",
    return: "1.23%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 3",
    name: 'ИСЖ ""Драйвер гарантия"" в долларах на на 3 года',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,65%\n0,95%",
    return: "0.95%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 4",
    name: 'ИСЖ "Киберспорт" в рублях/долларах на 5 лет',
    salesPoints: "",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "",
    currency: "",
    step: null,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 5",
    name: 'ИСЖ "Цифровая реальность" в рублях/долларах на 5 лет',
    salesPoints: "",
    path: "",
    regularityType: "",
    regularityValue: "",
    return: "",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "",
    currency: "",
    step: null,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ руб",
    name: 'ИСЖ "Драйвер гарантия" в рублях на 5 лет',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n4,7%\n5,2%",
    return: "5.20%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,000,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ руб",
    name: 'ИСЖ "Киберспорт" в рублях на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n72%\n100%",
    return: "8.80%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,000,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ руб",
    name: 'ИСЖ "Цифровая реальность" в рублях на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n80%\n100%",
    return: "10.00%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,000,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл",
    name: 'ИСЖ "Драйвер гарантия" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,93%\n1,23%",
    return: "1.23%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл",
    name: 'ИСЖ "Драйвер гарантия" в долларах на 3 года',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,65%\n0,95%",
    return: "0.95%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл",
    name: 'ИСЖ "Киберспорт" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n31%\n100%",
    return: "3.80%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл",
    name: 'ИСЖ "Цифровая реальность" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n34%\n100%",
    return: "4.60%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл Р",
    name: 'ИСЖ "Драйвер гарантия" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,93%\n1,23%",
    return: "1.23%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,197,152 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл Р",
    name: 'ИСЖ "Драйвер гарантия" в долларах на 3 года',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,65%\n0,95%",
    return: "0.95%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  2,197,152 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл Р",
    name: 'ИСЖ "Киберспорт" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n31%\n100%",
    return: "3.80%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,197,152 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ долл Р",
    name: 'ИСЖ "Цифровая реальность" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n34%\n100%",
    return: "4.60%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,197,152 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 6",
    name: 'ИСЖ "Киберспорт" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n31%\n100%",
    return: "3.80%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 6",
    name: 'ИСЖ "Цифровая реальность" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n34%\n100%",
    return: "4.60%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 7",
    name: 'ИСЖ "Драйвер гарантия" в долларах на 5 лет',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,93%\n1,23%",
    return: "1.23%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 7",
    name: 'ИСЖ "Драйвер гарантия" в долларах на 3 года',
    salesPoints:
      "Программа страхования с фиксированным доходом и 100% гарантией возврата средств.\nПреимущества продукта:\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Наследование\n- Юридическая защита\n- Режим конфиденциальности",
    path: "",
    regularityType:
      "Опциональность выплат\n - ежегодные выплаты:\n - выплата в конце срока:",
    regularityValue: "\n0,65%\n0,95%",
    return: "0.95%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 8",
    name: 'ИСЖ "Киберспорт" в рублях на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n72%\n100%",
    return: "8.80%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  2,000,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ИСЖ 8",
    name: 'ИСЖ "Цифровая реальность" в рублях на 5 лет',
    salesPoints:
      "Программа страхования с высокой потенциальной доходностью.\nПреимущества продукта:\n- Потенциально неограниченный инвестиционный доход\n- Гарантия возврата 100% капитала\n- Особый налоговый режим (НДФЛ с дохода снижается наставку рефинансирования)\n- Юридическая привилегии",
    path: "",
    regularityType:
      "Параметры программы\n - коэффициент участия\n - защита капитала",
    regularityValue: "\n80%\n100%",
    return: "10.00%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  30,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК с ЗК",
    name: "Автоколл Защищенная ставка №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nROSN/AFKS/NLMK/FEES\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "0%\n110%\n100%\nполуторагодовая",
    return: "10.00%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК с ЗК",
    name: "Автоколл Защищенная ставка №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nSNGSP/GAZP/LKOH/MAGN\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "0%\n110%\n100%\n20 месяцев",
    return: "11.00%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК с ЗК",
    name: "Автоколл Защищенная ставка №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nMTSS/MOEX/RSTI/CHMF\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "0%\n110%\n100%\n20 месяцев",
    return: "11.00%",
    risk: "",
    expirationDate: "14/12/2025",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК гарант",
    name: "Автоколл Ежемесячный постоянный купон",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nGAZP_LKOH_PLZL_YNDX",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nежемесячно",
    return: "17.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК гарант",
    name: "Автоколл Купонный платеж №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nALRS_MOEX_SIBN_VTBR",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nКвартальная",
    return: "14.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК гарант",
    name: "Автоколл Купонный платеж №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nAFLT_HYDR_MGNT_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "90%\n100%\n0%\nгодовая",
    return: "11.00%",
    risk: "",
    expirationDate: "15/12/2022",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК гарант",
    name: "Автоколл Купонный платеж №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nAFLT_HYDR_MGNT_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "95%\n100%\n0%\nполуторагодовая",
    return: "8.00%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК гарант",
    name: "Автоколл Флагманы цифровизации в РФ",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nTCSG/YNDX/SBER/MAIL\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nКвартальная",
    return: "14.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК гарант",
    name: "Автоколл Вклад в недвижимость №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nETLN_LSRG_PIKK",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "90%\n100%\n0%\nраз в два месяца",
    return: "15.00%",
    risk: "",
    expirationDate: "15/6/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК гарант",
    name: "Автоколл Вклад в недвижимость №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nETLN_LSRG_PIKK",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nраз в два месяца",
    return: "11.00%",
    risk: "",
    expirationDate: "15/6/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nALRS_MOEX_NLMK_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "0%\n110%\n100%\nполуторагодовая",
    return: "10.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nMGNT_MOEX_NLMK_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "0%\n110%\n100%\n20 месяцев",
    return: "11.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_LKOH_ROSN_YNDX",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "0%\n110%\n100%\n20 месяцев",
    return: "11.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл Нереализованный потенциал №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "18.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл Нереализованный потенциал №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nгодовая",
    return: "16.00%",
    risk: "",
    expirationDate: "15/12/2022",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл Нереализованный потенциал №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nГодовая",
    return: "16.00%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл Нефтегазовый сектор",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nSNGSP/NVTK/LKOH/SIBN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nПолугодовая",
    return: "20.00%",
    risk: "",
    expirationDate: "15/6/2022",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл 23-й купон",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nGAZP/GMKN/LKOH/YNDX\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "23.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК усл ЗК",
    name: "Автоколл Банки и финансы",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nMOEX/SBER/VTBR/TCSG\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячный",
    return: "17.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 гарант",
    name: "Автоколл Быстрый купон 45 дней",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nNLMK/SNGSP/MTSS/MOEX\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "92%\n100%\n0%\nВ конце срока",
    return: "16.00%",
    risk: "",
    expirationDate: "29/1/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 гарант",
    name: "Автоколл Быстрый купон 90 дней",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nNLMK/SNGSP/MTSS/MOEX\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "92%\n100%\n0%\nВ конце срока",
    return: "18.00%",
    risk: "",
    expirationDate: "15/3/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 гарант",
    name: "Автоколл Ежемесячный постоянный купон",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nGAZP_LKOH_PLZL_YNDX",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nежемесячно",
    return: "17.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 гарант",
    name: "Автоколл Купонный платеж №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nALRS_MOEX_SIBN_VTBR",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nКвартальная",
    return: "14.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 гарант",
    name: "Автоколл Флагманы цифровизации в РФ",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nTCSG/YNDX/SBER/MAIL\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nКвартальная",
    return: "14.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 гарант",
    name: "Автоколл Вклад в недвижимость №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nETLN_LSRG_PIKK",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "90%\n100%\n0%\nраз в два месяца",
    return: "15.00%",
    risk: "",
    expirationDate: "15/6/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 гарант",
    name: "Автоколл Вклад в недвижимость №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nETLN_LSRG_PIKK",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nраз в два месяца",
    return: "11.00%",
    risk: "",
    expirationDate: "15/6/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 усл ЗК",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nALRS_MOEX_NLMK_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "19.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 усл ЗК",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nMGNT_MOEX_NLMK_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "20.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 усл ЗК",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_LKOH_ROSN_YNDX",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "21.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 усл ЗК",
    name: "Автоколл Нереализованный потенциал №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "18.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 усл ЗК",
    name: "Автоколл 23-й купон",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nGAZP/GMKN/LKOH/YNDX\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "23.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 1 усл ЗК",
    name: "Автоколл Банки и финансы",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nMOEX/SBER/VTBR/TCSG\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячный",
    return: "17.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Ежемесячный постоянный купон",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nGAZP_LKOH_PLZL_YNDX",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nежемесячно",
    return: "17.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Купонный платеж №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nALRS_MOEX_SIBN_VTBR",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nКвартальная",
    return: "14.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Купонный платеж №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nAFLT_HYDR_MGNT_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "90%\n100%\n0%\nгодовая",
    return: "11.00%",
    risk: "",
    expirationDate: "15/12/2022",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Купонный платеж №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nAFLT_HYDR_MGNT_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "95%\n100%\n0%\nполуторагодовая",
    return: "8.00%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Флагманы цифровизации в РФ",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nTCSG/YNDX/SBER/MAIL\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n0%\nКвартальная",
    return: "14.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nALRS_MOEX_NLMK_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "19.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nMGNT_MOEX_NLMK_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "20.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл ЕЖЕМЕСЯЧНЫЙ ПОТЕНЦИАЛ №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_LKOH_ROSN_YNDX",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "21.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Нереализованный потенциал №1",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "18.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Нереализованный потенциал №2",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nгодовая",
    return: "16.00%",
    risk: "",
    expirationDate: "15/12/2022",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Нереализованный потенциал №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nГодовая",
    return: "16.00%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Нефтегазовый сектор",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nSNGSP/NVTK/LKOH/SIBN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nПолугодовая",
    return: "20.00%",
    risk: "",
    expirationDate: "15/6/2022",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл 23-й купон",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nGAZP/GMKN/LKOH/YNDX\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячно",
    return: "23.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 2",
    name: "Автоколл Банки и финансы",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nMOEX/SBER/VTBR/TCSG\n",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nежемесячный",
    return: "17.00%",
    risk: "",
    expirationDate: "15/12/2021",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 3",
    name: "Автоколл Купонный платеж №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nAFLT_HYDR_MGNT_SBERP",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "95%\n100%\n0%\nполуторагодовая",
    return: "8.00%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  400,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "АК 3",
    name: "Автоколл Нереализованный потенциал №3",
    salesPoints:
      "Внебиржевой опцион (Юр.ТИП) \nНаправлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину (продукт с риском)\nСостав портфеля:\nCHMF_MGNT_NLMK_ROSN",
    path: "",
    regularityType:
      "Порог поставки\nПорог отзыва\nКупонный порог\nПериодичность купона",
    regularityValue: "85%\n100%\n85%\nГодовая",
    return: "16.00%",
    risk: "",
    expirationDate: "15/12/2023",
    minAmount: "  250,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота гарант руб",
    name: "Отзывная нота на IT компании ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Европейский барьер)\n100%\n0%\n12,25%",
    return: "12.25%",
    risk: "",
    expirationDate: "15/5/2023",
    minAmount: "  100,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота гарант руб",
    name: "Отзывная нота на компании сектора кибербезопасности ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Европейский барьер)\n100%\n0%\n11,00%",
    return: "11.00%",
    risk: "",
    expirationDate: "19/6/2023",
    minAmount: "  100,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота гарант руб",
    name: "Отзывная нота на e-commerce компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n0%\n12,00%",
    return: "12.00%",
    risk: "",
    expirationDate: "7/8/2023",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота гарант долл",
    name: "Отзывная нота на нефтяные компании с Geared Put",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n0%\n7,50%",
    return: "7.50%",
    risk: "",
    expirationDate: "5/6/2023",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота гарант долл",
    name: "Отзывная нота на золотодобывающие компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n0%\n8,00%",
    return: "8.00%",
    risk: "",
    expirationDate: "4/9/2023",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота гарант долл",
    name: "Отзывная нота на контрциклические компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n0%\n8,50%",
    return: "8.50%",
    risk: "",
    expirationDate: "11/9/2023",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота гарант долл",
    name: "Отзывная нота на игровые компании ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "60% (Европейский барьер)\n100%\n0%\n8,00%",
    return: "8.00%",
    risk: "",
    expirationDate: "1/12/2023",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота руб",
    name: "Отзывная нота на компании сектора 5G с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n65%\n13,25%",
    return: "13.25%",
    risk: "",
    expirationDate: "12/6/2023",
    minAmount: "  100,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота руб",
    name: "Отзывная нота на депозитарные расписки российских компаний ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "55% (Европейский барьер)\n100%\n65%\n15,50%",
    return: "15.50%",
    risk: "",
    expirationDate: "19/6/2023",
    minAmount: "  1,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота руб",
    name: "Отзывная нота на компании сектора платежных систем с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n65%\n12,00%",
    return: "12.00%",
    risk: "",
    expirationDate: "17/9/2025",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал",
    name: "Отзывная нота на финансовые компании c Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "61% (Geared Put)\n100%\n75%\n9,00%",
    return: "9.00%",
    risk: "",
    expirationDate: "21/2/2025",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал",
    name: "Отзывная нота на золотодобывающие компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n65%\n12,50%",
    return: "12.50%",
    risk: "",
    expirationDate: "4/9/2023",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал",
    name: "Отзывная нота на контрциклические компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType: "0",
    regularityValue: "65% (Geared Put)\n100%\n65%\n12,50%",
    return: "12.50%",
    risk: "",
    expirationDate: "10/9/2025",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал",
    name: "Отзывная нота на игровые компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType: "0",
    regularityValue: "70% (Geared Put)\n100%\n70%\n10,00%",
    return: "10.00%",
    risk: "",
    expirationDate: "30/11/2023",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал",
    name: "Отзывная нота на авиакомпании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType: "0",
    regularityValue: "60% (Geared Put)\n100%\n60%\n16,00%",
    return: "16.00%",
    risk: "",
    expirationDate: "30/11/2023",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал Р",
    name: "Отзывная нота на финансовые компании c Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "61% (Geared Put)\n100%\n75%\n9,00%",
    return: "9.00%",
    risk: "",
    expirationDate: "21/2/2025",
    minAmount: "  73,238 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал Р",
    name: "Отзывная нота на золотодобывающие компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType:
      "Защита капитала\nБарьер автоотзыва\nКупонный барьер\nКупон",
    regularityValue: "65% (Geared Put)\n100%\n65%\n12,50%",
    return: "12.50%",
    risk: "",
    expirationDate: "4/9/2023",
    minAmount: "  73,238 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал Р",
    name: "Отзывная нота на контрциклические компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType: "0",
    regularityValue: "65% (Geared Put)\n100%\n65%\n12,50%",
    return: "12.50%",
    risk: "",
    expirationDate: "10/9/2025",
    minAmount: "  73,238 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал Р",
    name: "Отзывная нота на игровые компании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType: "0",
    regularityValue: "70% (Geared Put)\n100%\n70%\n10,00%",
    return: "10.00%",
    risk: "",
    expirationDate: "30/11/2023",
    minAmount: "  73,238 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "Нота вал Р",
    name: "Отзывная нота на авиакомпании с Geared Put ",
    salesPoints:
      "Нота - ценная бумага иностранного эмитента с рейтингом не ниже B- (Юр.ТИП), Продукт с риском(степень защиты), Выплата дохода в купонные даты (структура выплаты/регулярность). Продукт направлен на получение дохода в случае отcутствия существенного падения акций входящих в корзину\nСостав портфеля:\nAMZN_ATVI_EA_DIS_UBI",
    path: "",
    regularityType: "0",
    regularityValue: "60% (Geared Put)\n100%\n60%\n16,00%",
    return: "16.00%",
    risk: "",
    expirationDate: "30/11/2023",
    minAmount: "  73,238 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП глоб",
    name: "Модельный портфель глобальных акций",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Текущая структура по секторам\n- Технологии\n- Коммуникации\n- Финансы \n- Потребительские товары\n- Здравоохранение",
    regularityValue: "\n31%\n30%\n19%\n15%\n5%",
    return: "16.80%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП див",
    name: "Модельный портфель дивидендных акций",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Мы отдаем предпочтение устойчивым компаниям которые не просто платят высокие дивиденды, а ежегодно их повышают на протяжении длительного периода времени, например 20 50 лет",
    regularityValue:
      "Акции подобных компаний имеют характеристики инструментов с фиксированной доходностью, и фактически являются квази облигациями, по которым купон (в данном случае дивиденд) ежегодно увеличивается",
    return: "4.80%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП обл",
    name: "Модельный портфель облигаций в рублях",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Параметры портфеля\n- Доходность к погашению (YTM)\n- Купонная доходность\n- Дюрация",
    regularityValue: "\n6,9%\n8,62%\n2,9",
    return: "6.90%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП агр",
    name: "Модельный портфель Агрессивный",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Структура по классам активов\n- Акции\n- Облигации\n- Альтернативные интсрументы",
    regularityValue: "\n60%\n27%\n13%",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП конс",
    name: "Модельный портфель Консервативный",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Структура по классам активов\n- Акции\n- Облигации\n- Альтернативные интсрументы",
    regularityValue: "\n25%\n60%\n15%",
    return: "8.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП умерен",
    name: "Модельный портфель Умеренный",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Структура по классам активов\n- Акции\n- Облигации\n- Альтернативные интсрументы",
    regularityValue: "\n42%\n43%\n15%",
    return: "12.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП глоб $",
    name: "Модельный портфель глобальных акций",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Текущая структура по секторам\n- Технологии\n- Коммуникации\n- Финансы \n- Потребительские товары\n- Здравоохранение",
    regularityValue: "\n31%\n30%\n19%\n15%\n5%",
    return: "16.80%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  137 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП див $",
    name: "Модельный портфель дивидендных акций",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Мы отдаем предпочтение устойчивым компаниям которые не просто платят высокие дивиденды, а ежегодно их повышают на протяжении длительного периода времени, например 20 50 лет",
    regularityValue:
      "Акции подобных компаний имеют характеристики инструментов с фиксированной доходностью, и фактически являются квази облигациями, по которым купон (в данном случае дивиденд) ежегодно увеличивается",
    return: "4.80%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  137 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП агр $",
    name: "Модельный портфель Агрессивный",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Структура по классам активов\n- Акции\n- Облигации\n- Альтернативные интсрументы",
    regularityValue: "\n60%\n27%\n13%",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  137 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП конс $",
    name: "Модельный портфель Консервативный",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Структура по классам активов\n- Акции\n- Облигации\n- Альтернативные интсрументы",
    regularityValue: "\n25%\n60%\n15%",
    return: "8.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  137 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "МП умерен $",
    name: "Модельный портфель Умеренный",
    salesPoints:
      "Готовое решение для инвесторов\nМы предлагаем стратегию, которая основывается на портфельном подходе к распределению активов, которая позволяет получить максимальную доходность при заданном уровне риска, учитывая горизонт инвестирования для каждого клиента, исходя из его индивидуальных потребностей",
    path: "",
    regularityType:
      "Структура по классам активов\n- Акции\n- Облигации\n- Альтернативные интсрументы",
    regularityValue: "\n42%\n43%\n15%",
    return: "12.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  137 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФы обл",
    name: "Фонд «Открытие — Облигации» (ПИФ)",
    salesPoints:
      "Инвестиции в государственные облигации, облигации субъектов РФ и долговые обязательства компаний, по большей части номинированные в рублях, и банковские депозиты. Сильная диверсификация по отраслям и компаниям позволяет снизить волатильность стоимости пая. Фонд нацелен на превышение ставки по рублевым депозитам в среднесрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в рублях.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "9.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФы обл",
    name: "Фонд «Открытие — Еврооблигации»",
    salesPoints:
      "Основная часть активов - суверенные облигации и долговые обязательства компаний из стран ОЭСР и БРИКС в долларах. Эти инструменты доходнее долларовых депозитов в банках. Фонд нацелен на превышение ставки по долларовым депозитам в среднесрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в долларах США.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "6.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ еврообл",
    name: "Фонд «Открытие — Еврооблигации»",
    salesPoints:
      "Основная часть активов - суверенные облигации и долговые обязательства компаний из стран ОЭСР и БРИКС в долларах. Эти инструменты доходнее долларовых депозитов в банках. Фонд нацелен на превышение ставки по долларовым депозитам в среднесрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в долларах США.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "6.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ",
    name: "Фонд «Открытие — Акции» (ПИФ)",
    salesPoints:
      "Инвестиционная стратегия фонда предполагает активное управление, базирующееся на принципах долгосрочного инвестирования, диверсификации и эффективного риск-менеджмента. Инвестирование осуществляется преимущественно в недооцененные акции «первого» эшелона и наиболее перспективные акции «второго» эшелона с высоким потенциалом роста в долгосрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в рублях.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ",
    name: "Фонд «Открытие — Глобальные инвестиции» (ПИФ)",
    salesPoints:
      "Инвестиции в акции и биржевые фонды, диверсифицированный по классам активов портфель. Сбалансированная стратегия портфеля предполагает приобретение как высокорискованных, так и защитных инструментов, доли которых могут меняться в зависимости от рыночной конъюнктуры.",
    path: "",
    regularityType: "Доходность фонда выражена в рублях.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "10.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ",
    name: "Фонд «Открытие — Лидеры инноваций»",
    salesPoints:
      "Инвестиции в акции компаний технологического сектора с устойчивым конкурентным преимуществом и высокой доходностью на инвестированный капитал. Бумаги этого сектора, как правило, отличаются повышенной волатильностью, однако на долгосрочном горизонте инвестирования способны принести привлекательный доход.",
    path: "",
    regularityType: "Доходность фонда выражена в рублях.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ глоб",
    name: "Фонд «Открытие — Глобальные инвестиции» (ПИФ)",
    salesPoints:
      "Инвестиции в акции и биржевые фонды, диверсифицированный по классам активов портфель. Сбалансированная стратегия портфеля предполагает приобретение как высокорискованных, так и защитных инструментов, доли которых могут меняться в зависимости от рыночной конъюнктуры.",
    path: "",
    regularityType: "Доходность фонда выражена в долларах США.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "10.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "",
    name: "Фонд «Открытие — Облигации» (ПИФ)",
    salesPoints:
      "Инвестиции в государственные облигации, облигации субъектов РФ и долговые обязательства компаний, по большей части номинированные в рублях, и банковские депозиты. Сильная диверсификация по отраслям и компаниям позволяет снизить волатильность стоимости пая. Фонд нацелен на превышение ставки по рублевым депозитам в среднесрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в рублях.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "9.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "",
    name: "Фонд «Открытие — Еврооблигации»",
    salesPoints:
      "Основная часть активов - суверенные облигации и долговые обязательства компаний из стран ОЭСР и БРИКС в долларах. Эти инструменты доходнее долларовых депозитов в банках. Фонд нацелен на превышение ставки по долларовым депозитам в среднесрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в долларах США.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "6.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ 2",
    name: "Фонд «Открытие — Акции» (ПИФ)",
    salesPoints:
      "Инвестиционная стратегия фонда предполагает активное управление, базирующееся на принципах долгосрочного инвестирования, диверсификации и эффективного риск-менеджмента. Инвестирование осуществляется преимущественно в недооцененные акции «первого» эшелона и наиболее перспективные акции «второго» эшелона с высоким потенциалом роста в долгосрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в рублях.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ 2",
    name: "Фонд «Открытие — Лидеры инноваций»",
    salesPoints:
      "Инвестиции в акции компаний технологического сектора с устойчивым конкурентным преимуществом и высокой доходностью на инвестированный капитал. Бумаги этого сектора, как правило, отличаются повышенной волатильностью, однако на долгосрочном горизонте инвестирования способны принести привлекательный доход.",
    path: "",
    regularityType: "Доходность фонда выражена в долларах США.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  5,000 ",
    currency: "RUB",
    step: 5000,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ еврообл $",
    name: "Фонд «Открытие — Еврооблигации»",
    salesPoints:
      "Основная часть активов - суверенные облигации и долговые обязательства компаний из стран ОЭСР и БРИКС в долларах. Эти инструменты доходнее долларовых депозитов в банках. Фонд нацелен на превышение ставки по долларовым депозитам в среднесрочной перспективе.",
    path: "",
    regularityType: "Доходность фонда выражена в долларах США.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "6.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  68.3 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ПИФ глоб $",
    name: "Фонд «Открытие — Глобальные инвестиции» (ПИФ)",
    salesPoints:
      "Инвестиции в акции и биржевые фонды, диверсифицированный по классам активов портфель. Сбалансированная стратегия портфеля предполагает приобретение как высокорискованных, так и защитных инструментов, доли которых могут меняться в зависимости от рыночной конъюнктуры.",
    path: "",
    regularityType: "Доходность фонда выражена в долларах США.",
    regularityValue:
      "Доходы, возникающие в процессе управления паевым фондом, не облагается налогом. При владении паями более трех лет, налог с дохода от его продажи не взимается в пределах 3 млн рублей в год",
    return: "10.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  68.3 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ сбаланс руб",
    name: "ДУ Сбалансированная RUB",
    salesPoints:
      "Инвестиционная цель стратегии - сбалансированный доход с умеренной волатильностью, позволяющий рассчитывать на опережение доходности депозита на длительном временном горизонте, с меньшей вероятностью снижения стоимости активов, чем инвестирование 100% портфеля в акции.",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "12.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  1,000,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ сбаланс долл",
    name: "ДУ Сбалансированная USD",
    salesPoints:
      "Инвестиционная цель стратегии - сбалансированный доход с умеренной волатильностью, позволяющий рассчитывать на опережение доходности депозита на длительном временном горизонте, с меньшей вероятностью снижения стоимости активов, чем инвестирование 100% портфеля в акции.",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "8.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  150,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ лидеры",
    name: "ДУ Лидеры инноваций USD",
    salesPoints:
      "Инвестиционная цель стратегии - обеспечение долгосрочного прироста капитала за счет инвестирования в наиболее перспективные акции инновационных компаний",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  150,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ еврообл",
    name: "ДУ Еврооблигации USD",
    salesPoints:
      "Инвестиционная цель стратегии - обеспечить доходность выше банковских депозитов в долларах США и среднесрочных еврооблигаций с рейтингом от B- до BB+",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "5.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  300,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ рос акц",
    name: "ДУ Российские Акции RUB ",
    salesPoints:
      "Инвестиционная цель стратегии - обеспечение долгосрочного прироста капитала за счет инвестирования в наиболее перспективные темтические идеи на российском рынке акций",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  1,000,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ еврообл Р",
    name: "ДУ Еврооблигации USD",
    salesPoints:
      "Инвестиционная цель стратегии - обеспечить доходность выше банковских депозитов в долларах США и среднесрочных еврооблигаций с рейтингом от B- до BB+",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "5.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  21,971,520 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ сбаланс долл Р",
    name: "ДУ Сбалансированная USD",
    salesPoints:
      "Инвестиционная цель стратегии - сбалансированный доход с умеренной волатильностью, позволяющий рассчитывать на опережение доходности депозита на длительном временном горизонте, с меньшей вероятностью снижения стоимости активов, чем инвестирование 100% портфеля в акции.",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "8.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,985,760 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ДУ лидеры Р",
    name: "ДУ Лидеры инноваций USD",
    salesPoints:
      "Инвестиционная цель стратегии - обеспечение долгосрочного прироста капитала за счет инвестирования в наиболее перспективные акции инновационных компаний",
    path: "",
    regularityType: "Требуется заключить договор Доверительного управления.",
    regularityValue:
      "Стратегия предназначена для квалифицированного инвестора.",
    return: "15.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,985,760 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ЛБ",
    name: "Личный брокер",
    salesPoints:
      "Персональный инвестиционный консультант, который поможет структурировать ваши финансы и эффективно управлять капиталом.\n\nБолее 89% торговых идей в 2019 году показали прибыльный результат.",
    path: "",
    regularityType:
      "Тариф\n- Подключение сервиса\n- Комиссия с оборота на ФР\n- Комиссия с оборота на ВР",
    regularityValue: "\nбесплатно\n0.24%\n0.075%",
    return: "10.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  10,000 ",
    currency: "RUB",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
  {
    code: "ЛБ $",
    name: "Личный брокер",
    salesPoints:
      "Персональный инвестиционный консультант, который поможет структурировать ваши финансы и эффективно управлять капиталом.\n\nБолее 89% торговых идей в 2019 году показали прибыльный результат.",
    path: "",
    regularityType:
      "Тариф\n- Подключение сервиса\n- Комиссия с оборота на ФР\n- Комиссия с оборота на ВР",
    regularityValue: "\nбесплатно\n0.24%\n0.075%",
    return: "10.00%",
    risk: "",
    expirationDate: "16/12/2020",
    minAmount: "  1,000 ",
    currency: "USD",
    step: 1,
    price: "",
    qualification: "",
    plan: "",
    iisAvailibility: "",
    bonus: "",
    roa: "",
  },
];
